In [2]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 50)

In [ ]:
sales_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/sales_fact.csv")
products_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/products_master.csv")
suppliers_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/suppliers_master.csv")
inventory_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/inventory_snapshot.csv")

sales_product = sales_df.merge(products_df , on = 'sku_id' , how= 'left')

sales_product_supplier = sales_product.merge(suppliers_df , on = 'supplier_id' , how = 'left')

final_df = sales_product_supplier.merge(inventory_df , on = 'sku_id' , how = 'left')

In [4]:
sales_df.isnull().sum()

date                        0
sku_id                      0
units_sold                  0
selling_price               0
gross_revenue               0
promo_flag                  0
discount_pct                0
month                       0
week_of_year                0
day_of_week                 0
is_weekend                  0
is_festival_month           0
is_payday_period            0
season_tag                  0
holiday_flag                0
weather_index               0
campaign_intensity          0
platform_traffic_source     0
traffic_index               0
competitor_price_index      0
competitor_stockout_flag    0
bundle_offer_flag           0
stock_visibility_score      0
rating_score                0
review_volume               0
product_visibility_rank     0
dtype: int64

In [5]:
products_df.isnull().sum()

sku_id          0
sku_name        0
category        0
sub_category    0
mrp             0
cost_price      0
supplier_id     0
dtype: int64

In [6]:
inventory_df.isnull().sum()

sku_id                  0
current_stock           0
safety_stock            0
reorder_point           0
lead_time_days          0
inbound_shipment_qty    0
supplier_id             0
dtype: int64

In [7]:
suppliers_df.isnull().sum()

supplier_id              0
supplier_name            0
avg_lead_time            0
lead_time_variability    0
dtype: int64

In [8]:
sales_df.duplicated().sum()

np.int64(0)

In [9]:
products_df.duplicated().sum()

np.int64(0)

In [10]:
inventory_df.duplicated().sum()

np.int64(0)

In [11]:
suppliers_df.duplicated().sum()

np.int64(0)

In [12]:
# Primary Key Validation

products_df['sku_id'].duplicated().sum()

np.int64(0)

In [13]:
suppliers_df["supplier_id"].duplicated().sum()

np.int64(0)

In [14]:
sales_df[
    ~sales_df["sku_id"].isin(
        products_df["sku_id"]
    )
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [15]:
products_df[
    ~products_df["supplier_id"].isin(
        suppliers_df["supplier_id"]
    )
]

Empty DataFrame
Columns: [sku_id, sku_name, category, sub_category, mrp, cost_price, supplier_id]
Index: []

In [16]:
sales_df[
    sales_df['units_sold'] <0
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [17]:
# Negative Stock Validation

inventory_df[
    inventory_df['current_stock']<0
]

Empty DataFrame
Columns: [sku_id, current_stock, safety_stock, reorder_point, lead_time_days, inbound_shipment_qty, supplier_id]
Index: []

In [18]:
sales_df[
    sales_df['discount_pct']>100
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [19]:
products_df[
    products_df['cost_price'] > products_df['mrp']
]

Empty DataFrame
Columns: [sku_id, sku_name, category, sub_category, mrp, cost_price, supplier_id]
Index: []

In [20]:
sales_df["date"] = pd.to_datetime(
    sales_df["date"]
)

/var/folders/qm/8t8rxfy10f7b3mdcgk6yhkgh0000gp/T/ipykernel_58514/3586225470.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_df["date"] = pd.to_datetime(

In [21]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      14640 non-null  datetime64[ns]
 1   sku_id                    14640 non-null  object
 2   units_sold                14640 non-null  int64
 3   selling_price             14640 non-null  float64
 4   gross_revenue             14640 non-null  float64
 5   promo_flag                14640 non-null  int64
 6   discount_pct              14640 non-null  float64
 7   month                     14640 non-null  int64
 8   week_of_year              14640 non-null  int64
 9   day_of_week               14640 non-null  int64
 10  is_weekend                14640 non-null  int64
 11  is_festival_month         14640 non-null  int64
 12  is_payday_period          14640 non-null  int64
 13  season_tag                14640 non-null  object
 14  holiday_flag              14640 non-null  int64
 15  weather_index             14640 non-null  float64
 16  campaign_intensity        14640 non-null  int64
 17  platform_traffic_source   14640 non-null  object
 18  traffic_index             14640 non-null  float64
 19  competitor_price_index    14640 non-null  float64
 20  competitor_stockout_flag  14640 non-null  int64
 21  bundle_offer_flag         14640 non-null  int64
 22  stock_visibility_score    14640 non-null  float64
 23  rating_score              14640 non-null  float64
 24  review_volume             14640 non-null  int64
 25  product_visibility_rank   14640 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(14), object(3)
memory usage: 2.9+ MB