In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 50)

In [2]:
sales_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/sales_fact.csv")
products_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/products_master.csv")
suppliers_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/suppliers_master.csv")
inventory_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/inventory_snapshot.csv")

In [3]:
print(sales_df.shape)
print(products_df.shape)
print(inventory_df.shape)
print(suppliers_df.shape)

(14640, 26)
(40, 7)
(40, 7)
(10, 4)

In [4]:
sales_df.head()

,date,sku_id,units_sold,selling_price,gross_revenue,promo_flag,discount_pct,month,week_of_year,day_of_week,is_weekend,is_festival_month,is_payday_period,season_tag,holiday_flag,weather_index,campaign_intensity,platform_traffic_source,traffic_index,competitor_price_index,competitor_stockout_flag,bundle_offer_flag,stock_visibility_score,rating_score,review_volume,product_visibility_rank
0,1/1/24,SKU0001,28,1028.54,28799.12,0,0.0072,1,1,0,0,0,1,winter,0,1.033050,1,affiliate,1.028220,1.039897,0,0,0.332970,4.99,220,14
1,1/2/24,SKU0001,27,942.76,25454.52,0,0.0900,1,1,1,0,0,1,winter,0,1.075864,0,organic,1.000124,1.034213,0,0,0.332574,4.99,220,26
2,1/3/24,SKU0001,27,1023.78,27642.06,0,0.0118,1,1,2,0,0,1,winter,0,0.776739,0,paid,1.042157,1.019800,0,0,0.369938,4.99,220,50
3,1/4/24,SKU0001,29,940.90,27286.10,0,0.0918,1,1,3,0,0,1,winter,0,1.029230,0,paid,0.998036,1.004657,0,0,0.445269,4.99,220,42
4,1/5/24,SKU0001,37,812.43,30059.91,1,0.2158,1,1,4,0,0,1,winter,0,1.093677,1,organic,1.047220,0.956571,0,0,0.414885,4.99,220,20

In [6]:
products_df.head()

,sku_id,sku_name,category,sub_category,mrp,cost_price,supplier_id
0,SKU0001,NovaCharge Cable,Electronics Accessories,Audio,1036,731.48,SUP003
1,SKU0002,AirWave Earbuds,Beauty & Personal Care,Body Care,435,318.36,SUP007
2,SKU0003,GlowCare Serum,Home Cleaning,Multi-Surface,249,138.91,SUP006
3,SKU0004,FlexFit Yoga Mat,Electronics Accessories,Audio,532,290.52,SUP006
4,SKU0005,PureHome Dish Liquid,Electronics Accessories,Audio,654,477.19,SUP008

In [7]:
inventory_df.head()

,sku_id,current_stock,safety_stock,reorder_point,lead_time_days,inbound_shipment_qty,supplier_id
0,SKU0001,963,282,631,10,127,SUP003
1,SKU0002,581,213,428,6,36,SUP007
2,SKU0003,395,108,259,5,19,SUP006
3,SKU0004,375,113,274,5,40,SUP006
4,SKU0005,339,160,353,5,64,SUP008

In [8]:
suppliers_df.head()

  supplier_id              supplier_name  avg_lead_time  lead_time_variability
0      SUP001     EastBridge Trading Co.              3                      2
1      SUP002    NovaSupply Distributors             11                      4
2      SUP003  Skyline Imports Pvt. Ltd.             10                      2
3      SUP004        UrbanEdge Wholesale              3                      4
4      SUP005       PrimeRoute Logistics             13                      2

In [22]:
print('Sales Columns:\n', sales_df.columns)
print('======================================')
print('Products Columns:\n', products_df.columns)
print('======================================')
print('Inventory Columns:\n', inventory_df.columns)
print('======================================')
print('Suppliers Columns:\n', suppliers_df.columns)

Sales Columns:
 Index(['date', 'sku_id', 'units_sold', 'selling_price', 'gross_revenue',
       'promo_flag', 'discount_pct', 'month', 'week_of_year', 'day_of_week',
       'is_weekend', 'is_festival_month', 'is_payday_period', 'season_tag',
       'holiday_flag', 'weather_index', 'campaign_intensity',
       'platform_traffic_source', 'traffic_index', 'competitor_price_index',
       'competitor_stockout_flag', 'bundle_offer_flag',
       'stock_visibility_score', 'rating_score', 'review_volume',
       'product_visibility_rank'],
      dtype='object')
======================================
Products Columns:
 Index(['sku_id', 'sku_name', 'category', 'sub_category', 'mrp', 'cost_price',
       'supplier_id'],
      dtype='object')
======================================
Inventory Columns:
 Index(['sku_id', 'current_stock', 'safety_stock', 'reorder_point',
       'lead_time_days', 'inbound_shipment_qty', 'supplier_id'],
      dtype='object')
======================================
Suppliers Columns:
 Index(['supplier_id', 'supplier_name', 'avg_lead_time',
       'lead_time_variability'],
      dtype='object')

In [26]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      14640 non-null  object
 1   sku_id                    14640 non-null  object
 2   units_sold                14640 non-null  int64
 3   selling_price             14640 non-null  float64
 4   gross_revenue             14640 non-null  float64
 5   promo_flag                14640 non-null  int64
 6   discount_pct              14640 non-null  float64
 7   month                     14640 non-null  int64
 8   week_of_year              14640 non-null  int64
 9   day_of_week               14640 non-null  int64
 10  is_weekend                14640 non-null  int64
 11  is_festival_month         14640 non-null  int64
 12  is_payday_period          14640 non-null  int64
 13  season_tag                14640 non-null  object
 14  holiday_flag              14640 non-null  int64
 15  weather_index             14640 non-null  float64
 16  campaign_intensity        14640 non-null  int64
 17  platform_traffic_source   14640 non-null  object
 18  traffic_index             14640 non-null  float64
 19  competitor_price_index    14640 non-null  float64
 20  competitor_stockout_flag  14640 non-null  int64
 21  bundle_offer_flag         14640 non-null  int64
 22  stock_visibility_score    14640 non-null  float64
 23  rating_score              14640 non-null  float64
 24  review_volume             14640 non-null  int64
 25  product_visibility_rank   14640 non-null  int64
dtypes: float64(8), int64(14), object(4)
memory usage: 2.9+ MB

In [27]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sku_id        40 non-null     object
 1   sku_name      40 non-null     object
 2   category      40 non-null     object
 3   sub_category  40 non-null     object
 4   mrp           40 non-null     int64
 5   cost_price    40 non-null     float64
 6   supplier_id   40 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.3+ KB

In [29]:
inventory_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sku_id                40 non-null     object
 1   current_stock         40 non-null     int64
 2   safety_stock          40 non-null     int64
 3   reorder_point         40 non-null     int64
 4   lead_time_days        40 non-null     int64
 5   inbound_shipment_qty  40 non-null     int64
 6   supplier_id           40 non-null     object
dtypes: int64(5), object(2)
memory usage: 2.3+ KB

In [31]:
suppliers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   supplier_id            10 non-null     object
 1   supplier_name          10 non-null     object
 2   avg_lead_time          10 non-null     int64
 3   lead_time_variability  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes